### ISSUE TITLE
Is there a way to make this work with groups

### ISSUE THREAD

**Issue by bomsn** [stackadroit/cmb2-extensions#6]
The extension does not seem to work with group field as `render_row_cb` seem to retun empty arguements when used on a group field. How can we make it work with group fields?

**Comment by polupraneeth** [comment]
Right now the plugin doesn't support group fields, group fields support are in to do list.

**Comment by alexanderdejong** [comment]
Why don't you use the other [CMB2 tabs from LeadSoftInc](https://github.com/LeadSoftInc/cmb2-tabs)?

**Comment by polupraneeth** [comment]
we have updated the plugin and added the group fields feature in the cmb2 tabs plugin, group fields will work in tabs with CMB2 version 2.2.6 or greater.

[https://github.com/stackadroit/cmb2-extensions/wiki/CMB2-Tabs](Please refer the link of wiki as a guide)
`'render_row_cb' => array('CMB2_Tabs', 'tabs_render_group_row_cb'),`

**Comment by contempoinc** [comment]
Tried adding the above to my group but I'm getting a fatal error do you have a full example? Is it only supposed to be applied to the $group_field_id = $cmb_group->add_field() or every $cmb_group->add_group_field()

**Comment by polupraneeth** [comment]
@contempoinc, Hi the full example of a group can be found in "example-functions.php".

` /*******************GROUPS**************************/
    $group_field_id = $cmb_tabs_demo->add_field( array(
        'id'          => 'wiki_test_repeat_group',
        'type'        => 'group',
        'description' => __( 'Generates reusable form entries', 'cmb2_tabs' ),
        'tab'  => 'note',
        'render_row_cb' => array('CMB2_Tabs', 'tabs_render_group_row_cb'),
        // 'repeatable'  => false, // use false if you want non-repeatable group
        'options'     => array(
            'group_title'   => __( 'Entry {#}', 'cmb2_tabs' ), // since version 1.1.4, {#} gets replaced by row number
            'add_button'    => __( 'Add Another Entry', 'cmb2_tabs' ),
            'remove_button' => __( 'Remove Entry', 'cmb2_tabs' ),
            'sortable'      => true, // beta
            // 'closed'     => true, // true to have the groups closed by default
        ),
    ) );`

**Comment by contempoinc** [comment]
@polupraneeth Thanks, but yeah already tried exactly that and it won't display within a tab
