### ISSUE TITLE
Problems with sample setup

### ISSUE THREAD

**Issue by scarstens** [stackadroit/cmb2-extensions#8]
I just copied the sample function data into my plugin, and I got the following PHP warnings:

Warning: call_user_func() expects parameter 1 to be a valid callback, function 'cmb2_tabs_show_if_front_page' not found or invalid function name in /srv/www/brandreviews.test/public_html/wp-content/plugins/brand-review-crm/lib/cmb2-extensions/cmb2-tabs/cmb2-tabs.php on line 449

Notice: Accessing static property CMB2_Tabs::$cmb as non static in /srv/www/brandreviews.test/public_html/wp-content/plugins/brand-review-crm/lib/cmb2-extensions/cmb2-tabs/cmb2-tabs.php on line 449

Notice: Undefined property: CMB2_Tabs::$cmb in /srv/www/brandreviews.test/public_html/wp-content/plugins/brand-review-crm/lib/cmb2-extensions/cmb2-tabs/cmb2-tabs.php on line 449

![2018-03-21_23-16-50](https://user-images.githubusercontent.com/1483300/37754249-f5a84f7a-2d5d-11e8-96db-12aa4055f092.png)

**Comment by scarstens** [comment]
Appears to be related to these lines, which I simply commented out locally while setting up a sample to play with.

https://github.com/stackadroit/cmb2-extensions/blob/master/cmb2-tabs/example-functions.php#L57

https://github.com/stackadroit/cmb2-extensions/blob/master/cmb2-tabs/example-functions.php#L84

**Comment by polupraneeth** [comment]
I removed the undefined function from the example-functions.php.
